// Authentication errors
export const AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN';
export const AUTH_EXPIRED_TOKEN = 'AUTH_EXPIRED_TOKEN';
export const AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS';
export const AUTH_TOKEN_MISSING = 'AUTH_TOKEN_MISSING';
export const AUTH_REGISTRATION_FAILED = 'AUTH_REGISTRATION_FAILED';
export const AUTH_USER_EXISTS = 'AUTH_USER_EXISTS';

// Authorization errors
export const AUTHZ_INSUFFICIENT_ROLE = 'AUTHZ_INSUFFICIENT_ROLE';
export const AUTHZ_SPEC_DENIED = 'AUTHZ_SPEC_DENIED';
export const AUTHZ_FORBIDDEN = 'AUTHZ_FORBIDDEN';
export const AUTHZ_NOT_OWNER = 'AUTHZ_NOT_OWNER';

// Validation errors
export const VALIDATION_FAILED = 'VALIDATION_FAILED';
export const VALIDATION_MISSING_FIELD = 'VALIDATION_MISSING_FIELD';
export const VALIDATION_INVALID_FORMAT = 'VALIDATION_INVALID_FORMAT';
export const VALIDATION_INVALID_TYPE = 'VALIDATION_INVALID_TYPE';

// Resource errors
export const RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND';
export const RESOURCE_CONFLICT = 'RESOURCE_CONFLICT';
export const RESOURCE_GONE = 'RESOURCE_GONE';
export const RESOURCE_ALREADY_EXISTS = 'RESOURCE_ALREADY_EXISTS';

// Agent errors
export const AGENT_SESSION_LIMIT = 'AGENT_SESSION_LIMIT';
export const AGENT_TIMEOUT = 'AGENT_TIMEOUT';
export const AGENT_PROCESS_ERROR = 'AGENT_PROCESS_ERROR';
export const AGENT_SESSION_NOT_FOUND = 'AGENT_SESSION_NOT_FOUND';
export const AGENT_SESSION_TERMINATED = 'AGENT_SESSION_TERMINATED';
export const AGENT_INVALID_TYPE = 'AGENT_INVALID_TYPE';

// Git errors
export const GIT_CONFLICT = 'GIT_CONFLICT';
export const GIT_PUSH_FAILED = 'GIT_PUSH_FAILED';
export const GIT_NOT_INITIALIZED = 'GIT_NOT_INITIALIZED';
export const GIT_COMMIT_FAILED = 'GIT_COMMIT_FAILED';
export const GIT_DIFF_FAILED = 'GIT_DIFF_FAILED';
export const GIT_REPO_NOT_FOUND = 'GIT_REPO_NOT_FOUND';

// Graph errors
export const GRAPH_CYCLE_DETECTED = 'GRAPH_CYCLE_DETECTED';
export const GRAPH_INVALID_EDGE = 'GRAPH_INVALID_EDGE';
export const GRAPH_TRAVERSAL_ERROR = 'GRAPH_TRAVERSAL_ERROR';
export const GRAPH_NODE_NOT_FOUND = 'GRAPH_NODE_NOT_FOUND';

// Internal errors
export const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';
export const INTERNAL_DEPENDENCY_FAILURE = 'INTERNAL_DEPENDENCY_FAILURE';
export const INTERNAL_DATABASE_ERROR = 'INTERNAL_DATABASE_ERROR';
export const INTERNAL_SERVICE_UNAVAILABLE = 'INTERNAL_SERVICE_UNAVAILABLE';
