export const ERROR_CODES = {
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
  AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
  CONFLICT_ERROR: 'CONFLICT_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  RATE_LIMIT_ERROR: 'RATE_LIMIT_ERROR',

  SPEC_NOT_FOUND: 'SPEC_NOT_FOUND',
  SPEC_PERMISSION_DENIED: 'SPEC_PERMISSION_DENIED',
  SPEC_CONFLICT: 'SPEC_CONFLICT',

  EDGE_NOT_FOUND: 'EDGE_NOT_FOUND',
  EDGE_DUPLICATE: 'EDGE_DUPLICATE',
  EDGE_SELF_REFERENCE: 'EDGE_SELF_REFERENCE',
  EDGE_CIRCULAR: 'EDGE_CIRCULAR',

  DOCUMENT_NOT_FOUND: 'DOCUMENT_NOT_FOUND',

  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USERNAME_TAKEN: 'USERNAME_TAKEN',
  EMAIL_TAKEN: 'EMAIL_TAKEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',

  AGENT_SESSION_NOT_FOUND: 'AGENT_SESSION_NOT_FOUND',
  AGENT_SESSION_EXPIRED: 'AGENT_SESSION_EXPIRED',
  AGENT_UNAVAILABLE: 'AGENT_UNAVAILABLE',

  GIT_CONFLICT: 'GIT_CONFLICT',
  GIT_ERROR: 'GIT_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
